// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"io"

	"github.com/mattbriancon/pinchflat/internal/core"
)

func SearchHTMLShow(searchTerm string, searchResults []*core.MediaItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-header\"><h2 class=\"page-title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("Results for \"%s\"", searchTerm))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `searches__search_html__show.templ`, Line: 14, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h2></div><div class=\"card card-body\"><div class=\"max-w-full\"><div class=\"flex flex-col gap-6 dark:text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(searchResults) > 0 {
			templ_7745c5c3_Err = TableTable(TableProps{
				Rows:       toAny(searchResults),
				TableClass: "text-black dark:text-white",
				Columns: []TableColumn{
					{
						Label: "Title",
						Class: "cell-wrap",
						Render: func(row any) templ.Component {
							result := row.(*core.MediaItem)
							return TextSubtleLink(
								fmt.Sprintf("/sources/%v/media/%v", result.SourceID, result.ID),
								"",
								buildTitleComponent(result.Title),
							)
						},
					},
					{
						Label: "Excerpt",
						Class: "!whitespace-normal min-w-64",
						Render: func(row any) templ.Component {
							result := row.(*core.MediaItem)
							excerptText := ""
							if result.MatchingSearchTerm != nil {
								excerptText = *result.MatchingSearchTerm
							}
							return HighlightSearchTerms(excerptText)
						},
					},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p class=\"font-bold text-lg text-center text-black dark:text-white\">No results found</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Helper function to convert []*core.MediaItem to []any
func toAny(items []*core.MediaItem) []any {
	result := make([]any, len(items))
	for i, item := range items {
		result[i] = item
	}
	return result
}

// buildTitleComponent creates a component from a string title (pointer)
func buildTitleComponent(title *string) templ.Component {
	titleStr := ""
	if title != nil {
		titleStr = *title
	}
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, titleStr)
		return err
	})
}

var _ = templruntime.GeneratedTemplate
