// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/mattbriancon/pinchflat/internal/store"
)

// SourceFormProps is source_form/1's assigns.
type SourceFormProps struct {
	Form          *Form
	MediaProfiles []*store.MediaProfile
	Action        string
	Method        string
}

func SourceHTMLSourceForm(props SourceFormProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = CoreSimpleForm(
			templ.Attributes{
				"action": props.Action,
				"method": "post",
			},
			sourceFormBody(props),
			nil,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func sourceFormBody(props SourceFormProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.Method == "patch" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<input type=\"hidden\" name=\"_method\" value=\"patch\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Form.HasErrors() {
			templ_7745c5c3_Err = CoreError("Oops, something went wrong! Please check the errors below.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		f := props.Form
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section><section class=\"flex justify-between items-center mt-4\"><h3 class=\"section-title\">General Options</h3><span class=\"cursor-pointer hover:underline\" data-advanced-toggle>Editing Mode: <span data-advanced-label>Standard</span></span></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("original_url")),
			Type:  "text",
			Label: "Source URL",
			Help:  "URL of a channel or playlist (required)",
			Rest:  templ.Attributes{"autofocus": true},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("custom_name")),
			Type:  "text",
			Label: "Custom Name",
			Help:  "Does not impact indexing or downloading. Will be inferred from the source if left blank",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:   ptrField(f.Field("media_profile_id")),
			Options: MediaProfileOptions(props.MediaProfiles),
			Type:    "select",
			Label:   "Media Profile",
			Help:    "Sets your preferences for what media to look for and how to store it",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h3 class=\"mt-6 section-title\">Indexing Options</h3><section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:   ptrField(f.Field("index_frequency_minutes")),
			Options: FriendlyIndexFrequencyOptions(),
			Type:    "select",
			Label:   "Index Frequency",
			Help:    "Indexing is the process of checking for media to download. For best results, set this to the longest delay you can tolerate for this source",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("fast_index")),
			Type:  "toggle",
			Label: "Use Fast Indexing",
			Help:  "Not recommended for playlists. Overrides 'Index Frequency'. See below for more details (seriously, there's a TL;DR that's worth reading)",
			Rest: templ.Attributes{
				"data-disables":   `[name="source[index_frequency_minutes]"]`,
				"data-sets-value": "43200",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></section><h3 class=\"mt-6 section-title\">Downloading Options</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("download_media")),
			Type:  "toggle",
			Label: "Download Media",
			Help:  "Unchecking still indexes media but it won't be downloaded until you enable this option",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:   ptrField(f.Field("cookie_behaviour")),
			Options: FriendlyCookieBehaviourOptions(),
			Type:    "select",
			Label:   "Cookie Behaviour",
			Help:    "Uses your YouTube cookies for this source (if configured). 'When Needed' tries to minimize cookie usage except for certain indexing and downloading tasks. See docs",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<section data-advanced-only hidden>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("min_duration_seconds")),
			Type:  "number",
			Label: "Minimum Duration (seconds)",
			Help:  "Minimum duration of the media to be downloaded. Can be blank",
			Rest:  templ.Attributes{"min": "0"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("max_duration_seconds")),
			Type:  "number",
			Label: "Maximum Duration (seconds)",
			Help:  "Maximum duration of the media to be downloaded. Can be blank",
			Rest:  templ.Attributes{"min": "0"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</section><section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field: ptrField(f.Field("download_cutoff_date")),
			Type:  "text",
			Label: "Download Cutoff Date",
			Help:  "Only download media uploaded after this date. Leave blank to download all media. Must be in YYYY-MM-DD format. Old media may be deleted or downloaded if you change this date",
			Rest: templ.Attributes{
				"placeholder": "YYYY-MM-DD",
				"maxlength":   "10",
				"pattern":     `((?:19|20)[0-9][0-9])-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])`,
				"title":       "YYYY-MM-DD",
			},
			InputAppend: sourceFormCutoffDatePreset(f),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:    ptrField(f.Field("retention_period_days")),
			Type:     "number",
			Label:    "Retention Period (days)",
			Help:     "Days between when media is <em>downloaded</em> and when it's deleted. Leave blank to keep media indefinitely",
			HTMLHelp: true,
			Rest:     templ.Attributes{"min": "0"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<section data-advanced-only hidden><h3 class=\"mt-6 section-title\">Advanced Options</h3><p class=\"text-sm mt-2\">Tread carefully</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:    ptrField(f.Field("title_filter_regex")),
			Type:     "text",
			Label:    "Title Filter Regex",
			Help:     TitleFilterRegexHelp(),
			HTMLHelp: true,
			Rest:     templ.Attributes{"placeholder": "(?i)^How to Bike$"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Field:      ptrField(f.Field("output_path_template_override")),
			Type:       "text",
			InputClass: "font-mono",
			Label:      "Output path template override",
			Help:       OutputPathTemplateOverrideHelp(),
			HTMLHelp:   true,
			Rest: templ.Attributes{
				"data-placeholders":   OutputPathTemplateOverridePlaceholders(props.MediaProfiles),
				"data-profile-select": `[name="source[media_profile_id]"]`,
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</section></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ButtonButton("bg-primary", "rounded-lg", "my-6 w-full sm:w-auto", "submit", false, nil, sourceFormSaveText()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"rounded-sm dark:bg-meta-4 p-4 md:p-6 mb-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SourceHTMLFastIndexingHelp().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func sourceFormSaveText() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "Save Source")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func sourceFormCutoffDatePreset(f *Form) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = CoreInput(CoreInputProps{
			Prompt:     "Select preset",
			Name:       "download_cutoff_date_preset",
			Value:      "",
			Options:    CutoffDatePresetOptions(ctx),
			Type:       "select",
			InputClass: "w-30 lg:w-60 ml-2 md:ml-4",
			Rest: templ.Attributes{
				"data-fills":    `[name="source[download_cutoff_date]"]`,
				"data-fallback": InputValue(f.Field("download_cutoff_date").Value),
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ptrField hands CoreInput a *FormField the way Elixir passes f[:name]
// (a Phoenix.HTML.FormField struct) as the `field` assign.
func ptrField(f FormField) *FormField { return &f }

var _ = templruntime.GeneratedTemplate
