package app

import (
	"context"
	"fmt"
	"mime"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mattbriancon/pinchflat/internal/fsutil"
	"github.com/mattbriancon/pinchflat/internal/store"
)

// RssFeedBuilder builds RSS feeds for sources and their media items.

// RssFeedBuilderBuild/2. urlBase defaults to http://localhost:8945 when empty.
func (a *App) RssFeedBuilderBuild(ctx context.Context, source *store.Source, limit int, urlBase string) (string, error) {
	if urlBase == "" {
		urlBase = "http://localhost:8945"
	}

	// Get persisted media items
	mediaItems, err := a.PodcastHelpersPersistedMediaItemsFor(ctx, source, limit)
	if err != nil {
		return "", err
	}

	// Build and return the RSS feed XML
	return rssFeedBuilderBuildSourceXml(ctx, a, source, mediaItems, urlBase), nil
}

// rssFeedBuilderBuildSourceXml builds the RSS channel XML
func rssFeedBuilderBuildSourceXml(ctx context.Context, a *App, source *store.Source, mediaItems []*store.MediaItem, urlBase string) string {
	// Build media item XML
	var mediaItemXML []string
	for _, mediaItem := range mediaItems {
		itemXML := rssFeedBuilderBuildMediaItemXml(ctx, a, source, mediaItem, urlBase)
		mediaItemXML = append(mediaItemXML, itemXML)
	}

	// Cache the image path since it requires DB calls and is used twice
	feedImagePath := rssFeedBuilderFeedImagePath(ctx, a, urlBase, source, mediaItems)

	description := ""
	if source.Description != nil {
		description = *source.Description
	}

	lastBuildDate := formatRSSDate(source.UpdatedAt.Time)
	pubDate := formatRSSDate(source.InsertedAt.Time)
	selfLink := rssFeedBuilderGenerateSelfLink(urlBase, source)

	itemsJoined := strings.Join(mediaItemXML, "\n")

	uuid := ""
	if source.UUID != nil {
		uuid = *source.UUID
	}

	xml := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:podcast="https://podcastindex.org/namespace/1.0"
  xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>%s</title>
    <link>%s</link>
    <description>%s</description>
    <category>TV &amp; Film</category>
    <generator>Generated by Pinchflat</generator>
    <language>en-us</language>
    <lastBuildDate>%s</lastBuildDate>
    <pubDate>%s</pubDate>
    <atom:link href="%s" rel="self" type="application/rss+xml" />
    <podcast:locked>yes</podcast:locked>
    <podcast:guid>%s</podcast:guid>
    <image>
      <url>%s</url>
      <title>%s</title>
      <link>%s</link>
    </image>
    <itunes:author>%s</itunes:author>
    <itunes:subtitle>%s</itunes:subtitle>
    <itunes:block>yes</itunes:block>
    <itunes:image href="%s"></itunes:image>
    <itunes:explicit>false</itunes:explicit>
    <itunes:category text="TV &amp; Film"></itunes:category>

    %s

  </channel>
</rss>
`, fsutil.XMLSafe(source.CustomName), fsutil.XMLSafe(source.OriginalURL), fsutil.XMLSafe(description),
		lastBuildDate, pubDate, fsutil.XMLSafe(selfLink), uuid, fsutil.XMLSafe(feedImagePath),
		fsutil.XMLSafe(source.CustomName), fsutil.XMLSafe(source.OriginalURL),
		fsutil.XMLSafe(source.CustomName), fsutil.XMLSafe(source.CustomName), fsutil.XMLSafe(feedImagePath),
		itemsJoined)

	return xml
}

// rssFeedBuilderBuildMediaItemXml builds a single media item entry
func rssFeedBuilderBuildMediaItemXml(ctx context.Context, a *App, source *store.Source, mediaItem *store.MediaItem, urlBase string) string {
	itemImagePath := RssFeedBuilderItemImagePath(urlBase, mediaItem)

	title := ""
	if mediaItem.Title != nil {
		title = *mediaItem.Title
	}

	description := ""
	if mediaItem.Description != nil {
		description = *mediaItem.Description
	}

	durationSeconds := 0
	if mediaItem.DurationSeconds != nil {
		durationSeconds = *mediaItem.DurationSeconds
	}

	mediaSizeBytes := int64(0)
	if mediaItem.MediaSizeBytes != nil {
		mediaSizeBytes = *mediaItem.MediaSizeBytes
	}

	uploadedAt := formatRSSDate(mediaItem.UploadedAt.Time)
	mediaStreamPath := rssFeedBuilderMediaStreamPath(urlBase, mediaItem)
	mediaType := getMIMEType(mediaItem.MediaFilepath)

	itemImageLines := ""
	if itemImagePath != nil && *itemImagePath != "" {
		itemImageLines = fmt.Sprintf(`      <itunes:image href="%s"></itunes:image>
      <podcast:images srcset="%s" />`, fsutil.XMLSafe(*itemImagePath), fsutil.XMLSafe(*itemImagePath))
	}

	uuid := ""
	if mediaItem.UUID != nil {
		uuid = *mediaItem.UUID
	}

	xml := fmt.Sprintf(`    <item>
      <guid isPermaLink="false">%s</guid>
      <title>%s</title>
      <link>%s</link>
      <description>%s</description>
      <pubDate>%s</pubDate>
      <itunes:duration>%d</itunes:duration>
      <enclosure
        url="%s"
        length="%d"
        type="%s"
      />
      <itunes:author>%s</itunes:author>
      <itunes:subtitle>%s</itunes:subtitle>
      <itunes:summary><![CDATA[%s]]></itunes:summary>

      %s

      <itunes:explicit>false</itunes:explicit>
    </item>`, uuid, fsutil.XMLSafe(title), fsutil.XMLSafe(mediaItem.OriginalURL),
		fsutil.XMLSafe(description), uploadedAt, durationSeconds,
		fsutil.XMLSafe(mediaStreamPath), mediaSizeBytes, mediaType,
		fsutil.XMLSafe(source.CustomName), fsutil.XMLSafe(title),
		description, itemImageLines)

	return xml
}

// rssFeedBuilderGenerateSelfLink builds the self-link for the RSS feed
func rssFeedBuilderGenerateSelfLink(urlBase string, source *store.Source) string {
	uuid := ""
	if source.UUID != nil {
		uuid = *source.UUID
	}
	if !strings.HasSuffix(urlBase, "/") {
		urlBase += "/"
	}
	return urlBase + fmt.Sprintf("sources/%s/feed.xml", uuid)
}

// rssFeedBuilderMediaStreamPath builds the media stream URL
func rssFeedBuilderMediaStreamPath(urlBase string, mediaItem *store.MediaItem) string {
	ext := ""
	if mediaItem.MediaFilepath != nil {
		ext = filepath.Ext(*mediaItem.MediaFilepath)
	}
	uuid := ""
	if mediaItem.UUID != nil {
		uuid = *mediaItem.UUID
	}
	if !strings.HasSuffix(urlBase, "/") {
		urlBase += "/"
	}
	return urlBase + fmt.Sprintf("media/%s/stream%s", uuid, ext)
}

// rssFeedBuilderFeedImagePath gets the feed image path, checking for existence
func rssFeedBuilderFeedImagePath(ctx context.Context, a *App, urlBase string, source *store.Source, mediaItems []*store.MediaItem) string {
	imagePath, err := a.PodcastHelpersSelectCoverImage(ctx, source, mediaItems)
	if err != nil || imagePath == "" {
		return ""
	}

	ext := filepath.Ext(imagePath)
	uuid := ""
	if source.UUID != nil {
		uuid = *source.UUID
	}
	if !strings.HasSuffix(urlBase, "/") {
		urlBase += "/"
	}
	return urlBase + fmt.Sprintf("sources/%s/feed_image%s", uuid, ext)
}

// RssFeedBuilderItemImagePath checks if media item has a thumbnail and returns the path
func RssFeedBuilderItemImagePath(urlBase string, mediaItem *store.MediaItem) *string {
	if mediaItem.ThumbnailFilepath == nil || *mediaItem.ThumbnailFilepath == "" {
		return nil
	}

	// Check if file exists
	_, err := os.Stat(*mediaItem.ThumbnailFilepath)
	if err != nil {
		return nil
	}

	ext := filepath.Ext(*mediaItem.ThumbnailFilepath)
	uuid := ""
	if mediaItem.UUID != nil {
		uuid = *mediaItem.UUID
	}
	if !strings.HasSuffix(urlBase, "/") {
		urlBase += "/"
	}
	imagePath := urlBase + fmt.Sprintf("media/%s/episode_image%s", uuid, ext)
	return &imagePath
}

// formatRSSDate formats a time.Time to RSS date format: "Mon, 02 Jan 2006 15:04:05 -0700"
func formatRSSDate(t time.Time) string {
	// RFC1123 format with timezone
	return t.Format("Mon, 02 Jan 2006 15:04:05 -0700")
}

// getMIMEType returns the MIME type for a file path
func getMIMEType(filePath *string) string {
	if filePath == nil || *filePath == "" {
		return "application/octet-stream"
	}

	ext := filepath.Ext(*filePath)
	if mimeType := mime.TypeByExtension(ext); mimeType != "" {
		return mimeType
	}

	return "application/octet-stream"
}
